---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
spec:
  template:
    spec:
      containers:
        - image: localhost:5000/faas/helloworld-go:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: API_PORT
              value: "9000"